name: ci

on:
  push:

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - shell: sh
        env: 
          USERNAME:  ${{ secrets.DOCKERHUB_USERNAME }} 
        run: |
          echo  "%USENAME"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}     
